Repository Dev-Race/DevRace-backend, pull requests merged in 2024-05, with the labels that each got.

#2 [#1] Setting: 프로젝트 초기 세팅
  .DS_Store
  .github/.DS_Store
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/sajang/devracebackend/DevraceBackendApplication.java
  src/main/java/com/sajang/devracebackend/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: ⚙️ Setting

#4 [#3] Setting: CI/CD 파이프라인 및 Slack 환경 구축
  .ebextensions/00-set-timezone.config
  .ebextensions/01-rabbitmq.config
  .github/workflows/deploy.yml
  .github/workflows/slack-pr-open.yml
  .github/workflows/slack-pr-review.yml
  Dockerfile
  Dockerrun.aws.json
  build.gradle
Labels: ⚙️ Setting

#9 [#7] Feat: Response 및 Exception 처리 구성
  src/main/java/com/sajang/devracebackend/response/GlobalExceptionHandler.java
  src/main/java/com/sajang/devracebackend/response/ResponseCode.java
  src/main/java/com/sajang/devracebackend/response/ResponseData.java
  src/main/java/com/sajang/devracebackend/response/exception/CrawlingServerException.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException400.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException404.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/BojIdDuplicateException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/ChatBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/ProblemBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/RoomBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/UserBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/UserRoomBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchBojIdException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchChatException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchProblemException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchRoomException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchUserException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchUserRoomException.java
  src/main/java/com/sajang/devracebackend/response/responseitem/MessageItem.java
  src/main/java/com/sajang/devracebackend/response/responseitem/StatusItem.java
Labels: ✨ Feat

#18 [#16] Test: SpringBootTest 어노테이션 제거 후 빌드 시도
  src/test/java/com/sajang/devracebackend/DevraceBackendApplicationTests.java
Labels: ✅ Test

#20 [#19] Refactor: 엔티티 등의 리팩토링 및 DI 주입
  build.gradle
  src/main/java/com/sajang/devracebackend/DevraceBackendApplication.java
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/domain/Chat.java
  src/main/java/com/sajang/devracebackend/domain/Problem.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/domain/common/BaseEntity.java
  src/main/java/com/sajang/devracebackend/domain/enums/Language.java
  src/main/java/com/sajang/devracebackend/domain/enums/MessageType.java
  src/main/java/com/sajang/devracebackend/domain/enums/Role.java
  src/main/java/com/sajang/devracebackend/domain/enums/RoomState.java
  src/main/java/com/sajang/devracebackend/domain/enums/SocialType.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/domain/problem/Problem.java
  src/main/java/com/sajang/devracebackend/domain/user/Role.java
  src/main/java/com/sajang/devracebackend/domain/user/SocialType.java
  src/main/java/com/sajang/devracebackend/repository/ChatRepository.java
  src/main/java/com/sajang/devracebackend/repository/ProblemRepository.java
  src/main/java/com/sajang/devracebackend/repository/RoomRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/TokenServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#22 [#21] Fix: Swagger Cors 문제로 server url 추가 작성
  src/main/java/com/sajang/devracebackend/config/SwaggerConfig.java
Labels: 🐛 Fix

#24 [#23] Feat: WebClient 외부 API 호출 메소드 작성
  build.gradle
  src/main/java/com/sajang/devracebackend/dto/user/SolvedResponseDto.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#26 [#25] Fix: Entity 속성 삭제 및 추가
  src/main/java/com/sajang/devracebackend/domain/Problem.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: 🐛 Fix

#34 [#27] Feat: 백준 문제 크롤링 및 DB 저장
  build.gradle
  src/main/java/com/sajang/devracebackend/domain/Problem.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemDto.java
  src/main/java/com/sajang/devracebackend/service/ProblemService.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
Labels: ✨ Feat

#36 [#35] Refactor: Problem 크롤링 관련 리팩토링
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/domain/Problem.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemDto.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemResponseDto.java
  src/main/java/com/sajang/devracebackend/service/ProblemService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#37 [#32] Feat: OAuth2 소셜 로그인 및 회원가입
  build.gradle
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/dto/auth/SignupRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/SignupResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/TokenDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/response/responseitem/MessageItem.java
  src/main/java/com/sajang/devracebackend/security/jwt/JwtExceptionFilter.java
  src/main/java/com/sajang/devracebackend/security/jwt/JwtFilter.java
  src/main/java/com/sajang/devracebackend/security/jwt/TokenProvider.java
  src/main/java/com/sajang/devracebackend/security/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/sajang/devracebackend/security/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/sajang/devracebackend/security/oauth2/CustomOAuth2User.java
  src/main/java/com/sajang/devracebackend/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/sajang/devracebackend/security/oauth2/OAuthAttributes.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sajang/devracebackend/security/oauth2/userinfo/GithubOAuth2UserInfo.java
  src/main/java/com/sajang/devracebackend/security/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/sajang/devracebackend/security/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/AwsS3Service.java
  src/main/java/com/sajang/devracebackend/service/TokenService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/AwsS3ServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/TokenServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
  src/main/resources/static/index.html
Labels: ✨ Feat

#38 [#33] Feat: JWT 토큰 만료 reissue 재발급 기능 완성
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/dto/auth/ReissueRequestDto.java
  src/main/java/com/sajang/devracebackend/response/GlobalExceptionHandler.java
  src/main/java/com/sajang/devracebackend/response/ResponseCode.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/TokenBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/responseitem/MessageItem.java
  src/main/java/com/sajang/devracebackend/security/jwt/TokenProvider.java
  src/main/java/com/sajang/devracebackend/service/TokenService.java
  src/main/java/com/sajang/devracebackend/service/impl/TokenServiceImpl.java
Labels: ✨ Feat

#40 [#39] Docs: README.md 작성
  README.md
Labels: 📝 Docs

#42 [#41] Feat: 방 생성 기능
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/domain/Problem.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomIdResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/ProblemRepository.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/StringListConverter.java
Labels: ✨ Feat

#44 [#43] Feat: 참여중인 방 여부 검사 기능
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemSaveRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomSaveResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserEnterResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserSolvedResponseDto.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#47 [#46] Refactor: AllArgsConstructor를 Builder 패턴으로 리팩토링
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/dto/auth/SignupResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/TokenDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomSaveResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserEnterResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserSolvedResponseDto.java
  src/main/java/com/sajang/devracebackend/security/oauth2/OAuthAttributes.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#48 [#45] Feat: 여러 사용자 동시 입장 기능
  build.gradle
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/domain/Chat.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatSaveRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserCurrentRoomResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserEnterRequestDto.java
  src/main/java/com/sajang/devracebackend/repository/ChatRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#50 [#49] Feat: 실시간 대기열 STOMP 통신 기능
  README.md
  src/main/java/com/sajang/devracebackend/DevraceBackendApplication.java
  src/main/java/com/sajang/devracebackend/config/RabbitConfig.java
  src/main/java/com/sajang/devracebackend/config/StompConfig.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomEnterRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomWaitRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomWaitResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserEnterRequestDto.java
  src/main/java/com/sajang/devracebackend/security/jwt/JwtChannelInterceptor.java
  src/main/java/com/sajang/devracebackend/security/jwt/handler/JwtStompExceptionHandler.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: ✨ Feat

#55 [#54] Fix: RabbitMQ 재활성화
  src/main/java/com/sajang/devracebackend/config/RabbitConfig.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
Labels: 🐛 Fix

#61 [#54] Fix: build 설정 수정
  build.gradle
Labels: 🐛 Fix

#62 [#54] Fix: 빌드 설정 Rollback
  src/main/java/com/sajang/devracebackend/config/RabbitConfig.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
Labels: ✅ Test

#63 [#54] Test: RabbitMQ 재활성화 후 배포 테스트
  src/main/java/com/sajang/devracebackend/config/RabbitConfig.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
Labels: ✅ Test

#65 [#54] Fix: postdeploy 디렉토리 생성문 추가
  .github/workflows/deploy.yml
Labels: 🐛 Fix

#66 [#54] Fix: chmod 설정 파일 분리
  .ebextensions/01-chmod-postdeploy.config
  .ebextensions/02-rabbitmq.config
Labels: 🐛 Fix

#67 [#54] Fix: chmod content라인 추가
  .ebextensions/01-chmod-postdeploy.config
Labels: 🐛 Fix

#69 [#54] Fix: deploy.yml 에러 해결
  .github/workflows/deploy.yml
Labels: 🐛 Fix

#70 [#54] Fix: postdeploy 플랫폼 재분리
  .ebextensions/01-chmod-postdeploy.config
  .ebextensions/01-rabbitmq.config
  .github/workflows/deploy.yml
  .platform/hooks/postdeploy/connect_spring_to_network.sh
Labels: 🐛 Fix

#74 [#73] Fix: Docker Network 예외처리 작성
  .platform/hooks/postdeploy/connect_spring_to_network.sh
Labels: 🐛 Fix

#75 [#73] Fix: postdeploy 예외처리 수정
  .platform/hooks/postdeploy/connect_spring_to_network.sh
Labels: 🐛 Fix

#77 [#76] Test: AWS docker network CI/CD 테스트
  .platform/hooks/postdeploy/connect_spring_to_network.sh
Labels: ✅ Test

#80 [#78] Feat: 문제풀이 페이지 정보 조회 기능
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomCheckStateResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserCheckRoomResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/RoomCheckAccessResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/SolvingPageResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#82 [#81] Fix: 회원가입 API http method 수정
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
Labels: 🐛 Fix

#84 [#83] Feat: 회원 프로필 조회 기능
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#86 [#85] Refactor: JWT Access Token 만료시간 단축 리팩토링
  src/main/java/com/sajang/devracebackend/security/jwt/TokenProvider.java
Labels: ♻️ Refactor

#87 [#85] Fix: 배포 서버 rabbitmq enable 문제 해결
  .DS_Store
  .ebextensions/01-rabbitmq.config
  .github/workflows/deploy.yml
  src/main/java/com/sajang/devracebackend/security/jwt/TokenProvider.java
Labels: 🐛 Fix

#88 [#54] Fix: RabbitMQ 컨테이너 삭제 설정 추가
  .ebextensions/01-rabbitmq.config
Labels: 🐛 Fix

#89 [#54] Fix: rabbitmq plugins true 설정
  .ebextensions/01-rabbitmq.config
Labels: 🐛 Fix

#90 [#79] Feat: 문제풀이 성공 및 실패에 따른 UserRoom 상태값 변경
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/dto/userroom/CheckIsPassDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/StringListConverter.java
Labels: ✨ Feat

#92 [#91] Refactor: Problem 관련 예외처리 리팩토링
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/dto/userroom/UserPassRequestDto.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/StringListConverter.java
Labels: ♻️ Refactor

#96 [#93] Feat: 실시간 랭킹 및 채팅 STOMP 통신 기능
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/domain/Chat.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomCheckStateResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/SolvingPageResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/ChatService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: ✨ Feat

#100 [#99] Refactor: 채팅 비즈니스 로직 리팩토링
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
Labels: ♻️ Refactor

#101 [#54] Fix: Swap 메모리 생성 설정
  .ebextensions/01-set-swapmemory.config
  .ebextensions/02-rabbitmq.config
Labels: 🐛 Fix

#102 [#99] Refactor: 대기자 명단 접속순으로 변경
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
Labels: ♻️ Refactor

#104 [#103] Feat: 채팅방 무한 스크롤 Slice 페이징 기능
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/repository/ChatRepository.java
  src/main/java/com/sajang/devracebackend/service/ChatService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#106 [#105] Feat: 코드방 조회/정렬/검색 Page 페이징 기능
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/dto/userroom/CodeRoomResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: ✨ Feat

#108 [#107] Refactor: 회원가입 이미지 전송 리팩토링
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
Labels: ♻️ Refactor

#112 [#111] Refactor: Chat 엔티티 및 비즈니스 로직 리팩토링
  src/main/java/com/sajang/devracebackend/DevraceBackendApplication.java
  src/main/java/com/sajang/devracebackend/domain/Chat.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatResponseDto.java
  src/main/java/com/sajang/devracebackend/security/oauth2/OAuthAttributes.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#114 [#113] Feat: 회원 탈퇴 기능
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: ✨ Feat

#116 [#115] Refactor: N+1 문제 해결 및 JPA 쿼리 성능 개선
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: ♻️ Refactor
