Repository Dev-Race/DevRace-backend, pull requests merged in 2024-06, with the labels that each got.

#118 [#117] Refactor: Exception 구조 및 처리 리팩토링
  README.md
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/response/GlobalExceptionHandler.java
  src/main/java/com/sajang/devracebackend/response/ResponseCode.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException400.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException404.java
  src/main/java/com/sajang/devracebackend/response/exception/CustomException500.java
  src/main/java/com/sajang/devracebackend/response/exception/Exception400.java
  src/main/java/com/sajang/devracebackend/response/exception/Exception404.java
  src/main/java/com/sajang/devracebackend/response/exception/Exception500.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/BojIdDuplicateException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/ChatBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/ProblemBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/RoomBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/TokenBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/UserBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception400/UserRoomBadRequestException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchBojIdException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchChatException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchProblemException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchRoomException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchUserException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception404/NoSuchUserRoomException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception500/AwsS3ServerException.java
  src/main/java/com/sajang/devracebackend/response/exception/exception500/CrawlingServerException.java
  src/main/java/com/sajang/devracebackend/response/responseitem/MessageItem.java
  src/main/java/com/sajang/devracebackend/security/jwt/handler/JwtExceptionFilter.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/AwsS3ServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ProblemServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/TokenServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/SecurityUtil.java
Labels: ♻️ Refactor

#120 [#119] Fix: 페이징 content 빈값 문제
  src/main/java/com/sajang/devracebackend/repository/ChatRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: 🐛 Fix

#122 [#121] Refactor: Fetch Join 추가 리팩토링 및 성능 개선
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/domain/Room.java
  src/main/java/com/sajang/devracebackend/domain/User.java
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/RoomRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#124 [#123] Refactor: 채팅방 페이징 정렬기준 및 날짜형식 리팩토링
  src/main/java/com/sajang/devracebackend/config/RabbitConfig.java
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/response/GlobalExceptionHandler.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
Labels: ♻️ Refactor

#128 [#127] Refactor: Swagger API 명세 리팩토링
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
Labels: ♻️ Refactor

#129 [#39] Docs: README 프로젝트 설명 작성
  README.md
Labels: 📝 Docs

#131 [#130] Fix: Fetch inner Join으로 인한 404 에러 문제
  src/main/java/com/sajang/devracebackend/dto/room/RoomResponseDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomRepository.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: 🐛 Fix

#133 [#132] Refactor: TokenService AuthService 통합 리팩토링
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/TokenService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/TokenServiceImpl.java
Labels: ♻️ Refactor

#134 [#39] Docs: Notification 작성
  README.md
Labels: 📝 Docs

#136 [#135] File: 미사용 DTO 클래스 파일 삭제
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomEnterRequestDto.java
Labels: 📁 File

#137 [#39] Docs: README 프로젝트 설명 수정
  README.md
Labels: 📝 Docs

#141 [#140] Refactor: Batch Delete 성능 개선 리팩토링
  README.md
  src/main/java/com/sajang/devracebackend/repository/UserRoomBatchRepository.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/test/java/com/sajang/devracebackend/service/AuthServiceTest.java
  src/test/java/com/sajang/devracebackend/service/UserRoomServiceTest.java
Labels: ♻️ Refactor

#142 [#39] Docs: CI/CD 아키텍처 작성
  README.md
Labels: 📝 Docs

#143 [#39] Docs: README Introduction 작성
  README.md
Labels: 📝 Docs

#145 [#144] Refactor: Dto Inner Class 리펙토링
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/dto/AuthDto.java
  src/main/java/com/sajang/devracebackend/dto/ChatDto.java
  src/main/java/com/sajang/devracebackend/dto/ProblemDto.java
  src/main/java/com/sajang/devracebackend/dto/RoomDto.java
  src/main/java/com/sajang/devracebackend/dto/UserDto.java
  src/main/java/com/sajang/devracebackend/dto/UserRoomDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/ReissueRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/SignupRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/SignupResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/auth/TokenDto.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/chat/ChatResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/problem/ProblemSaveRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomCheckStateResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomWaitRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/room/RoomWaitResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserCheckRoomResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserSolvedResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/user/UserUpdateRequestDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/CodeRoomResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/RoomCheckAccessResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/SolvingPageResponseDto.java
  src/main/java/com/sajang/devracebackend/dto/userroom/UserPassRequestDto.java
  src/main/java/com/sajang/devracebackend/security/jwt/TokenProvider.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/ChatService.java
  src/main/java/com/sajang/devracebackend/service/RoomService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/RoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
Labels: ♻️ Refactor

#148 [#147] Refactor: 메소드 순서 및 네이밍 리팩토링
  src/main/java/com/sajang/devracebackend/controller/AuthController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
  src/main/java/com/sajang/devracebackend/controller/TestController.java
  src/main/java/com/sajang/devracebackend/controller/UserController.java
  src/main/java/com/sajang/devracebackend/dto/AuthDto.java
  src/main/java/com/sajang/devracebackend/dto/UserRoomDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRepository.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/ChatService.java
  src/main/java/com/sajang/devracebackend/service/UserRoomService.java
  src/main/java/com/sajang/devracebackend/service/UserService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/ChatServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
  src/main/java/com/sajang/devracebackend/service/impl/UserServiceImpl.java
Labels: ♻️ Refactor

#150 [#149] Feat: URI Security 접근제한 적용
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/controller/ChatController.java
  src/main/java/com/sajang/devracebackend/controller/RoomController.java
Labels: ✨ Feat

#151 [#149] Fix: Cors 로컬 도메인 FE 수정
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
Labels: 🐛 Fix

#153 [#152] Test: 회원가입 권한 확인 테스트
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
Labels: ✅ Test

#154 [#152] Fix: 회원가입시 RefreshToken null 업데이트 문제 해결
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sajang/devracebackend/service/AuthService.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
Labels: 🐛 Fix

#155 [#152] Fix: 리다이렉트 쿼리스트링 Rollback
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 🐛 Fix

#156 [#152] Refactor: SecurityConfig 권한 판별 메소드로 이동
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/SecurityUtil.java
Labels: ♻️ Refactor

#157 [#152] Test: signup API 권한 해제 테스트
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
Labels: ✅ Test

#158 [#152] Test: All URI permitAll 적용 테스트
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
Labels: ✅ Test

#159 [#152] Fix: 회원가입 권한 403 문제 해결
  README.md
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sajang/devracebackend/service/impl/AuthServiceImpl.java
  src/main/java/com/sajang/devracebackend/util/SecurityUtil.java
Labels: 🐛 Fix

#161 [#160] Fix: JDBC insert 시간값 null 문제
  src/main/java/com/sajang/devracebackend/domain/mapping/UserRoom.java
  src/main/java/com/sajang/devracebackend/dto/UserRoomDto.java
  src/main/java/com/sajang/devracebackend/repository/UserRoomBatchRepository.java
  src/main/java/com/sajang/devracebackend/service/impl/UserRoomServiceImpl.java
Labels: 🐛 Fix

#163 [#162] Refactor: JDBC Batch 2차 성능 개선 리팩토링
  src/main/java/com/sajang/devracebackend/repository/UserRoomBatchRepository.java
  src/test/java/com/sajang/devracebackend/service/AuthServiceTest.java
Labels: ♻️ Refactor

#165 [#164] Fix: 사용자 프로필 조회 API 권한 추가
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
Labels: 🐛 Fix

#167 [#166] Fix: AWS S3 null 이미지 삭제 방지
  src/main/java/com/sajang/devracebackend/config/SecurityConfig.java
  src/main/java/com/sajang/devracebackend/service/impl/AwsS3ServiceImpl.java
Labels: 🐛 Fix

#168 [#39] Docs: Demo 시연 사진 및 영상 첨부
  README.md
Labels: 📝 Docs
